name: Revisión con Gemini
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Revisión IA
        uses: google-github-actions/run-gemini-cli@v0.1.6
        with:
          prompt: |
            Actúa como revisor experto.
            Señala errores y propone mejoras.
            Responde en español.
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
